<?php

namespace Bedycasa\Bundle\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getProducts()
    {
        $products = $this->findAll();

        $array = array();

        foreach($products as $key => $product)
        {
            $array[$product->getId()] = $product->getName();
        }

        return $array;
    }
}
