<?php
namespace Bedycasa\Bundle\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductInBasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductInBasketRepository extends EntityRepository
{
}