parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: bedycasa
    database_user: root
    database_password: pass

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    locale: en
    secret: 12d6dde55174e7216d9b30e8793e5b2a

    database_path: null
